---
title: "Exploration"
author: "A09"
date: "12/04/2021"
output: html_document
---

[delete later] test pull and push

```{r}

# Libraries
library(readxl)
library(tidyverse)
library(ggplot2)
library(zoo) # For computing moving averages 
library(GGally)

```

### Load, clean and reformat data

```{r}

flow_2020= read_excel("Flow 2020.xlsx", sheet=2, na="NA")
eu_2020= read_excel("EU 2020 .xlsx", sheet=2, na="NA")
flow_2019= read_excel("Flow 2019.xlsx", sheet=2, na="NA")
eu_2019= read_excel("EU 2019 .xlsx", sheet=2, na="NA")

# Load price data and add to the generation dataset
price_2019= read_excel("Price 2019.xlsx") %>% 
  mutate(Datetime = ISOdate(year,month, day, hour), .after = year) %>% 
  select(5:18)
price_2020 = read_excel("Price 2020.xlsx")


price <- rbind(price_2019, price_2020)

# Join data for 2020 and 2019
eu_generation <- rbind(eu_2019, eu_2020)

# Make interconnector flows between GB and its neighbors consistent with the rest of the dataset
flow_2020 <- flow_2020 %>% 
  mutate(GB.FR= -FR.GB,
         GB.NL = -NL.GB,
         GB.BE= -BE.GB,
         GB.IE= -IE.GB,
         GB.NIR= -NIR.GB
         )

flow_2019 <- flow_2019 %>% 
  mutate(GB.FR= -FR.GB,
         GB.NL = -NL.GB,
         GB.BE= -BE.GB,
         GB.IE= -IE.GB,
         GB.NIR= -NIR.GB
         )

flow <- rbind(flow_2019, flow_2020)


# Load data on the carbon intensities of each generation technology

carbon_intensities <- read_excel("Technology CO2 Intensity.xlsx") 
carbon_intensities <- carbon_intensities[3, 2:21]

```

## Calculation of carbon intensity 

```{r}

# Calculate total generation and compute difference between demand and generation
eu_generation <- eu_generation %>% 
  mutate(Generation= rowSums(dplyr::across(3:22), na.rm = T),
         Difference= Generation-Demand) 


# Percentage of total generation from each fuel/asset type-Hourly
eu_generation_percentage <- as.data.frame(cbind(eu_generation %>% select(1:2), 
                                                (eu_generation %>% select(3:22))/rowSums((eu_generation %>% select(3:22))),
                                                eu_generation %>% select(Generation,Demand, Difference)))

eu_generation_CI <- 
  eu_generation_percentage %>% 
  select(3:22)

eu_generation_CI <- cbind(eu_generation_percentage %>% select(Datetime, Country), 
                          as.data.frame(mapply("*", eu_generation_CI, carbon_intensities)))

# Calculate the total hourly carbon intensity of each Megawatt hour of energy generated by each country (in kg/MWh or g/KWh)
eu_generation_CI <- 
  eu_generation_CI %>% 
  mutate(carbon_intensity = 1000*rowSums(dplyr::across(3:22), na.rm = T))

# Dataframe of hourly carbon intensities for each country

hourly_carbon_intensity <- eu_generation_CI %>% 
  select(Datetime, Country, carbon_intensity) %>% 
  pivot_wider(names_from = "Country", values_from= "carbon_intensity")


# Add price and carbon intensity to the dataframe containing proportions of total generation from each fuel/asset type
eu_generation_percentage <- eu_generation_percentage %>% 
  left_join(price %>% pivot_longer(cols= 2:14, names_to= "Country", values_to= "Price"), by =c("Datetime", "Country")) %>% 
  left_join(eu_generation_CI %>% select(Datetime, Country, carbon_intensity),  by =c("Datetime", "Country"))



```

### Calculation of carbon savings of interconnector flows 

```{r}

# Create the notin operator
`%notin%` <- Negate(`%in%`)

# Store list of countries whose carbon intensities have been calculated
country_names <- unlist(colnames(hourly_carbon_intensity))

# Join hourly country carbon intensities and flow data
  
flow_plus_CI <- left_join(flow, hourly_carbon_intensity, by="Datetime") %>% 
  mutate_at(2:60, function(x) ifelse(x>0,0,x))


# Remove columns containing countries whose carbon intensities is unknown

p=61
i=2

while(i<p){
  flow_names <- unlist(str_split(colnames(flow_plus_CI[,i]), "\\."))
  if( flow_names[1] %notin% country_names |  flow_names[2] %notin% country_names){
    flow_plus_CI <- flow_plus_CI[-c(i)]
    i=i-1
    p=p-1
  }
  i=i+1
}


# Calculate carbon savings of imports (A.B -> A imports from B)
for(i in 2:46){
  flow_names <- unlist(str_split(colnames(flow_plus_CI[,i]), "\\."))
  flow_plus_CI[,i] <- abs(flow_plus_CI[,i])*(flow_plus_CI[, flow_names[1]]- flow_plus_CI[, flow_names[2]])
}


carbon_savings_df <- flow_plus_CI %>% 
  select(-c(47:60))

# Calculate total carbon savings in the two years
colSums(carbon_savings_df %>% select(-Datetime))


```

### Plot 2 month moving average for the carbon intensities of Britain, Germany, France, Norway, Sweden

```{r, fig.height=8, fig.width=12, warning=FALSE}


eu_generation_percentage %>% 
  filter(Country == "GB") %>%
  mutate(carbon_intensity_MA= rollmean(carbon_intensity, k = 1440, fill = NA)) %>% 
  ggplot(aes(x = Datetime, y = carbon_intensity_MA))+
  geom_line() +
  labs(title = "60-Day Moving Average for the Carbon Intensity of Britain")


eu_generation_percentage %>% 
  filter(Country == "DE") %>% 
  mutate(carbon_intensity_MA= rollmean(carbon_intensity, k = 1440, fill = NA)) %>%
  ggplot(aes(x = Datetime, y = carbon_intensity_MA))+
  geom_line() +
  labs(title = "60-Day  Moving Average for the Carbon Intensity of Germany")

eu_generation_percentage %>% 
  filter(Country == "FR") %>% 
  mutate(carbon_intensity_MA = rollmean(carbon_intensity, k = 1440, fill = NA)) %>%
  ggplot(aes(x = Datetime, y = carbon_intensity_MA))+
  geom_line() +
  labs(title = "60-Day  Moving Average for the Carbon Intensity of France")

eu_generation_percentage %>% 
  filter(Country == "NO") %>% 
  mutate(carbon_intensity_MA = rollmean(carbon_intensity, k = 1440, fill = NA)) %>%
  ggplot(aes(x = Datetime, y = carbon_intensity_MA))+
  geom_line() +
  labs(title = "60-Day  Moving Average for the Carbon Intensity of Norway")


eu_generation_percentage %>% 
  filter(Country == "SE") %>% 
  mutate(carbon_intensity_MA = rollmean(carbon_intensity, k = 1440, fill = NA)) %>%
  ggplot(aes(x = Datetime, y = carbon_intensity_MA))+
  geom_line() +
  labs(title = "60-Day  Moving Average for the Carbon Intensity of Swedan")


```


### Plot 2 week moving average for the demand of Britain, Germany, France, Norway, Sweden

```{r, fig.height=8, fig.width=12, warning=FALSE}


eu_generation_percentage%>% 
  filter(Country == "GB") %>%
  mutate(demand_MA = rollmean(Demand, k = 336, fill = NA)) %>% 
  ggplot(aes(x = Datetime, y = demand_MA))+
  geom_line() +
  labs(title = "14 Day Moving Average for the Demand of Britain")

eu_generation_percentage%>% 
  filter(Country == "FR") %>%
  mutate(demand_MA = rollmean(Demand, k = 336, fill = NA)) %>% 
  ggplot(aes(x = Datetime, y = demand_MA))+
  geom_line() +
  labs(title = "14 Day Moving Average for the Demand of France")

eu_generation_percentage %>% 
  filter(Country == "NO") %>%
  mutate(demand_MA = rollmean(Demand, k = 336, fill = NA)) %>% 
  ggplot(aes(x = Datetime, y = demand_MA))+
  geom_line() +
  labs(title = "14 Day Moving Average for the Demand of Norway")

eu_generation_percentage %>% 
  filter(Country == "SE") %>%
  mutate(demand_MA = rollmean(Demand, k = 336, fill = NA)) %>% 
  ggplot(aes(x = Datetime, y = demand_MA))+
  geom_line() +
  labs(title = "14 Day Moving Average for the Demand of Swedan")

eu_generation_percentage %>% 
  filter(Country == "DE") %>%
  mutate(demand_MA = rollmean(Demand, k = 336, fill = NA)) %>% 
  ggplot(aes(x = Datetime, y = demand_MA))+
  geom_line() +
  labs(title = "14 Day Moving Average for the Demand of Germany")



```

### Great Britain and Belgium

```{r fig.height=8, fig.width=12}


GB_generation_data <- eu_generation_percentage %>% 
  filter(Country== "GB")


GB_generation_data %>% 
  mutate(Price_MA= rollmean(Price, k = 336, fill = NA)) %>% 
  ggplot(aes(x= Datetime, y= Price_MA)) +
  geom_line()+
  theme_minimal()+
  labs(
    title= "Change in price in Great Britain over time (14-day moving average)",
    y="Price (Pounds per MWh)",
    x=element_blank()
  )+
  theme(plot.title = element_text(size = 16, face = "bold"))


GB_generation_data %>% 
  mutate(carbon_intensity_MA= rollmean(carbon_intensity, k = 1440, fill = NA)) %>% 
  ggplot(aes(x= Datetime, y= carbon_intensity_MA)) +
  geom_line()+
  theme_minimal()+
  labs(
    title= "Change in carbon intensity in Great Britain over time (60-day moving average)",
    y="Carbon Intensity (kg/MWh)",
    x= element_blank()
  )+
  theme(plot.title = element_text(size = 16, face = "bold"))


```


```{r fig.height=8, fig.width=12}

BE_generation_data <- eu_generation_percentage %>% 
  filter(Country== "BE")


BE_generation_data %>% 
  mutate(Price_MA= rollmean(Price, k = 336, fill = NA)) %>% 
  ggplot(aes(x= Datetime, y= Price_MA)) +
  geom_line()+
  theme_minimal()+
  labs(
    title= "Change in price in Belgium over time (14-day moving average)",
    y="Price (Pounds per MWh)",
    x=element_blank()
  )+
  theme(plot.title = element_text(size = 16, face = "bold"))


BE_generation_data %>% 
  mutate(carbon_intensity_MA= rollmean(carbon_intensity, k = 1440, fill = NA)) %>% 
  ggplot(aes(x= Datetime, y= carbon_intensity_MA)) +
  geom_line()+
  theme_minimal()+
  labs(
    title= "Change in carbon intensity in Belgium over time (60-day moving average)",
    y="Carbon Intensity (kg/MWh)",
    x= element_blank()
  )+
  theme(plot.title = element_text(size = 16, face = "bold"))


# 60-day moving average of hourly carbon intensities of all countries 

hourly_carbon_intensity_MA <- as.data.frame(hourly_carbon_intensity %>% 
  select(2:15) %>% 
  rollapply(1440, mean, by.column= TRUE))


hourly_carbon_intensity_MA <-  cbind(hourly_carbon_intensity %>%select(Datetime) %>% tail(-1439), hourly_carbon_intensity_MA)
 
hourly_carbon_intensity_MA %>%  
  pivot_longer(cols=2:15, names_to="Country", values_to= "carbon_intensity") %>% 
  ggplot(aes(x= Datetime, y= carbon_intensity, color= Country))+
  geom_line(size=0.8)+
  theme_minimal()+
  labs(
    title= "Change in carbon intensity of European countries over time (60-day moving average)",
    y="Carbon Intensity (kg/MWh)",
    x= element_blank()
  )+
  theme(plot.title = element_text(size = 16, face = "bold"))+
   scale_color_manual(values= c('#e6194b', '#3cb44b', '#ffe119', '#4363d8', '#f58231', '#911eb4', '#46f0f0', '#f032e6', '#bcf60c', '#fabebe', '#008080', '#e6beff', '#9a6324', '#fffac8'))


```


```{r fig.height=8, fig.width=12}

carbon_savings_df %>% 
  mutate(carbon_savings_GB.FR_MA= rollmean(GB.FR, k = 1440, fill = NA)) %>% 
  ggplot(aes(x= Datetime, y= carbon_savings_GB.FR_MA/1000))+
  geom_line()+
  theme_minimal()+
  labs(
    title= "Carbon savings through IFA over time (60-day moving average)",
    y="Carbon Savings (Tons)",
    x= element_blank()
  )+
  theme(plot.title = element_text(size = 16, face = "bold"))
  

carbon_savings_df %>% 
  summarise(GB.FR= sum(GB.FR, na.rm= TRUE),
            GB.NL = sum(GB.NL, na.rm= TRUE),
            GB.BE = sum(GB.BE, na.rm= TRUE),
            GB.IE = sum(GB.IE, na.rm= TRUE)
            ) %>% 
  pivot_longer(cols= 1:4, names_to= "int_name", values_to= "carbon_savings") %>% 
  ggplot(aes(x=int_name, y=carbon_savings/1e9))+
  geom_col(width=0.3)+
  theme_minimal()+
  labs(
    title= "Total carbon savings through interconnectors (Britain)",
    y="Carbon Savings (Megatons of Co2)",
    x= element_blank()
  )+
  theme(plot.title = element_text(size = 16, face = "bold"))

carbon_savings_df %>% 
  summarise(BE.GB = sum(BE.GB, na.rm= TRUE),
            BE.DE = sum(BE.DE, na.rm= TRUE),
            BE.NL = sum(BE.NL, na.rm= TRUE),
            BE.FR = sum(BE.FR, na.rm= TRUE)
            ) %>% 
  pivot_longer(cols= 1:4, names_to= "int_name", values_to= "carbon_savings") %>% 
  ggplot(aes(x=int_name, y=carbon_savings/1e9))+
  geom_col(width=0.3)+
  theme_minimal()+
  labs(
    title= "Total carbon savings through interconnectors (Belgium)",
    y="Carbon Savings (Megatons of Co2)",
    x= element_blank()
  )+
  theme(plot.title = element_text(size = 16, face = "bold"))





```

