---
title: "Forecasting"
author: "A09"
date: "12/04/2021"
output: html_document
---

```{r}

# Libraries
library(readxl)
library(tidyverse)
library(ggplot2)
library(zoo) # For computing moving averages 
library(GGally)
library(caret) 
library(lubridate)
library(rsample)
library(tseries)
library(forecast)
library(vars)
library(car)
library(HDeconometrics)
library(Metrics)

```

### Load ,clean and reformat data

```{r}
#Import flow and generation data 2019-2020
flow_2020= read_excel("Flow 2020.xlsx", sheet=2, na="NA")
eu_2020= read_excel("EU 2020 .xlsx", sheet=2, na="NA")
flow_2019= read_excel("Flow 2019.xlsx", sheet=2, na="NA")
eu_2019= read_excel("EU 2019 .xlsx", sheet=2, na="NA")

# Import flow and generation data from 2016-2018
flow_1618 <- read_excel("flow_2016_2018.xlsx")
eu_1618 <- read_csv("EU 2016-18.csv")

# Import demand data for France
#demand_1618 <- read_csv("Demand_FR.csv")

# Load data on the carbon intensities of each generation technology
carbon_intensities <- read_excel("Technology CO2 Intensity.xlsx") 
carbon_intensities <- carbon_intensities[3, 2:21]

# Join data for 2020 and 2019
eu_1920 <- rbind(eu_2019, eu_2020) %>% 
# Remove negative generation, calculate total generation and compute difference between demand and generation
   mutate_at(3:23, function(x) ifelse(x<0,0,x)) 

# Make interconnector flows between GB and its neighbors consistent with the rest of the dataset
flow_2020 <- flow_2020 %>% 
  mutate(GB.FR= -FR.GB,
         GB.NL = -NL.GB,
         GB.BE= -BE.GB,
         GB.IE= -IE.GB,
         GB.NIR= -NIR.GB
         )

flow_2019 <- flow_2019 %>% 
  mutate(GB.FR= -FR.GB,
         GB.NL = -NL.GB,
         GB.BE= -BE.GB,
         GB.IE= -IE.GB,
         GB.NIR= -NIR.GB
         )

# Convert flow and generation data to monthly
flow_1920 <- as.data.frame(rbind(flow_2019, flow_2020)) %>%
  mutate(Datetime= floor_date(Datetime, "month")) %>% 
  group_by(Datetime) %>% 
  summarise_at(1:59, sum, na.rm=TRUE) 
  
  
eu_1920 <- eu_1920 %>% 
  mutate(Datetime= floor_date(Datetime, "month")) %>% 
  group_by(Country, Datetime) %>% 
  summarise_at(1:21, sum, na.rm=TRUE) 



```

```{r fig.height=8, fig.width=12}

fr_1920 <- eu_1920 %>% 
  filter(Country=="FR") %>%
  dplyr::select(-20,-21)

fr_1618 <- eu_1618 %>% 
  filter(Country=="France (FR)") %>% 
  dplyr::select(-2) %>% 
  left_join(demand_1618, by="Datetime")

FR_data <- as.data.frame(rbind(fr_1618, fr_1920)) %>% 
mutate(Renewables= Geothermal+Hydro.Pumped.Storage+ Hydro.Run.of.river.and.poundage+
                  Hydro.Water.Reservoir+ Nuclear+ Solar+Wind.Offshore+Wind.Onshore+
                 Other.renewable, .after="Wind.Onshore")  %>% 
dplyr::select(-c(9:13, 15:16, 18:19))


fr_flow_1920 <- flow_1920 %>% 
  dplyr::select(c(1,33,35:38)) %>% 
  mutate(Datetime= floor_date(Datetime, "month")) %>% 
  group_by(Datetime) %>% 
  summarise_at(1:5, sum, na.rm=TRUE) 
  

fr_flow_1618 <- flow_1618 %>% 
  dplyr::select(c(1, 4, 11, 13,7,9))

FR_data <- FR_data %>% 
  left_join(as.data.frame(rbind(fr_flow_1618,fr_flow_1920)), by="Datetime") %>% 
  dplyr::select(-c(3:4, 8:9))

FR_data %>% 
  dplyr::select(1,2:13) %>% 
  pivot_longer(cols= 2:13, names_to= "Type", values_to= "Values") %>% 
  ggplot(aes(x=Datetime, y=Values, color=Type)) +
  geom_line()

```


## Initial calculation of carbon intensity 

```{r}

# Remove negative generation, calculate total generation and compute difference between demand and generation
eu_generation <- eu_generation %>% 
  mutate_at(3:22, function(x) ifelse(x<0,0,x)) %>% 
  mutate(Generation= rowSums(dplyr::across(3:22), na.rm = T),
         Difference= Generation-Demand) 

# Percentage of total generation from each fuel/asset type-Hourly
eu_generation_percentage <- as.data.frame(cbind(eu_generation %>% select(1:2), (eu_generation %>% select(3:22))/rowSums((eu_generation %>% select(3:22))), eu_generation %>% select(Generation,Demand, Difference)))

eu_generation_CI <- 
  eu_generation_percentage %>%
  select(3:22)

eu_generation_CI <- cbind(eu_generation_percentage %>% select(Datetime, Country), as.data.frame(mapply("*", eu_generation_CI, carbon_intensities)))

# Calculate the total hourly carbon intensity of each Megawatt hour of energy generated by each country (in kg/MWh or g/KWh)
eu_generation_CI <- 
  eu_generation_CI %>% 
  mutate(carbon_intensity = 1000*rowSums(dplyr::across(3:22), na.rm = T))

# Dataframe of hourly carbon intensities for each country

hourly_carbon_intensity <- eu_generation_CI %>% 
  select(Datetime, Country, carbon_intensity) %>% 
  pivot_wider(names_from = "Country", values_from= "carbon_intensity")


# Add price and carbon intensity to the dataframe containing proportions of total generation from each fuel/asset type
eu_generation_percentage <- eu_generation_percentage %>% 
  left_join(eu_generation_CI %>% select(Datetime, Country, carbon_intensity),  by =c("Datetime", "Country"))


hourly_generation <- eu_generation %>% 
  select(Datetime, Country, Generation) %>% 
  pivot_wider(names_from = "Country", values_from= "Generation")

write_csv(hourly_carbon_intensity, "hourly_carbon_intensity.csv")
write_csv(hourly_generation, "hourly_generation.csv")

```

### Vector Autoregression

#### Daily Data

```{r fig.height=8, fig.width=12}

GB_data <- read_excel("GB_Data.xlsx", sheet=1) %>% 
  mutate(Datetime= floor_date(ymd_hms(Datetime),"day")) 

original_data <- GB_data %>% 
  group_by(Datetime) %>% 
  summarise_at(1:12, sum) 

GB_data <- GB_data %>% 
  group_by(Datetime) %>% 
  summarise_at(1:12, sum) %>% 
  dplyr::select(-1)

# Split into training and test sets
GB_data_train <- GB_data[1:710,]
GB_data_test <- GB_data[711:731,]

# Run the augmented dickey-fuller test on all time-series to check for stationarity
apply(GB_data_train,2,adf.test)

# Difference each time series to make them all stationary 
GB_data_train <- as.data.frame(apply(GB_data_train,2, diff, differences = 1))

lagselect <- VARselect(GB_data_train %>% dplyr::select(1:12), lag.max = 40, type = "const")
lagselect$selection

Model1 <- VAR(GB_data_train %>% dplyr::select(1:12), p = 40, type = "const", season = NULL, exog = NULL) 
summary(Model1)

# Test for serial correlation in the residuals 
serial.test(Model1, lags.pt=40, type = "PT.asymptotic")

# Since we reject the null hypothesis that there is no serial correlation the model still has autocorrelation between the errors : there is still variance that is not explained by the model

# Test for causality
#causality(Model1 , cause = "Demand", vcov.=NULL, boot=FALSE, boot.runs=100)

# Make predictions
forecast <- predict(Model1, n.ahead = 21, ci = 0.95)

forecast <- as.data.frame(forecast$fcst) %>% 
  dplyr::select(1,5,9,13,17,21,25,29,33,37,41,45)

forecast <- as.matrix(forecast)

forecast <- as.data.frame(diffinv(forecast, lag=1, xi= as.matrix(GB_data[710,])))

new_names <- colnames(GB_data_test)
old_names <- colnames(forecast)

values = seq(from = as.Date("2020-12-10"), to = as.Date("2020-12-31"), by = 'day')

forecast <- forecast %>% 
rename_at(vars(old_names), ~ new_names) %>% 
mutate(Datetime = values, .before= Biomass)

forecast_dat <- forecast %>% 
  slice(2:22) %>% 
   mutate_at(2:8, function(x) ifelse(x<0,0,x)) %>% 
  dplyr::select(-1)

test_dat <- original_data %>% 
  slice(711:731) %>% 
  dplyr::select(-1)

rmse(as.matrix(forecast_dat), as.matrix(test_dat))
mae(as.matrix(forecast_dat), as.matrix(test_dat))

```


```{r}

# Split into training and test sets
FR_data_train <- FR_data[1:50,] %>% 
  dplyr::select(-1)
FR_data_test <- FR_data[51:60,]

# Run the augmented dickey-fuller test on all time-series to check for stationarity
apply(FR_data_train,2,adf.test)

# Difference each time series to make them all stationary 
FR_data_train <- as.data.frame(apply(FR_data_train,2, diff, differences = 1))

last_value <- as.matrix(FR_data_train[49,])

lagselect <- VARselect(FR_data_train, lag.max = 40, type = "const")
lagselect$selection

Model1 <- VAR(FR_data_train, p = 1, type = "const", season = NULL, exog = NULL) 
summary(Model1)

# Test for serial correlation in the residuals 
serial.test(Model1, lags.pt=1, type = "PT.asymptotic")

# Make predictions
forecast <- predict(Model1, n.ahead = 10, ci = 0.95)

forecast <- as.data.frame(forecast$fcst) %>% 
  dplyr::select(1,5,9,13,17,21,25,29,33,37,41,45)

forecast <- as.matrix(forecast)

forecast <- as.data.frame(diffinv(forecast, lag=1, xi= last_value))
forecast <- as.data.frame(diffinv(as.matrix(forecast %>% slice(2:11)), lag=1, xi= as.matrix(FR_data[50,] %>% dplyr::select(-1))))

new_names <- colnames(FR_data_test)
old_names <- colnames(forecast)

values = seq(from = as.Date("2020-03-01"), to = as.Date("2020-12-01"), by = 'month')

forecast <- forecast %>% 
slice(2:11) %>% 
mutate(Datetime = values, .before= "V1") %>% 
rename_at(vars(old_names), ~ new_names) 




```





